server:
  port: 8083
spring:
  application:
    name: security-workflow-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/mahasetu}

management:
  endpoints:
    web:
      exposure:
        include: health,info
