server:
  port: 8083
spring:
  application:
    name: security-workflow-service
  datasource:
    url: ${WORKFLOW_DB_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:ep-proud-tree-a5mvkwlf-pooler.us-east-2.aws.neon.tech}:${DB_PORT:5432}/${DB_NAME:mahasetu_workflow}?sslmode=require}}
    username: ${WORKFLOW_DB_USER:${DB_USER:neondb_owner}}
    password: ${WORKFLOW_DB_PASSWORD:${DB_PASSWORD:npg_n7J6NReErVwU}}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/mahasetu
          jwk-set-uri: http://keycloak:8080/realms/mahasetu/protocol/openid-connect/certs
      client:
        registration:
          security-workflow-service:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${SECURITY_WORKFLOW_CLIENT_ID:security-workflow-service}
            client-secret: ${SECURITY_WORKFLOW_CLIENT_SECRET:}
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/mahasetu/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

spring.flyway.enabled: true
spring.flyway.baseline-on-migrate: true
spring.flyway.baseline-version: 0
spring.flyway.table: flyway_schema_history_workflow

camunda:
  bpm:
    auto-deployment-enabled: true
    database:
      schema-update: true
    job-execution:
      enabled: false
    history-level: full

mahasetu:
  application-service:
    url: ${APPLICATION_SERVICE_URL:http://localhost:8081}
  interoperability-service:
    url: ${INTEROPERABILITY_SERVICE_URL:http://localhost:8082}
    token: ${INTEROPERABILITY_SERVICE_TOKEN:MAHASETU_SUPER_SECRET_TOKEN_2026}
  consent-policy:
    policies:
      SKILL_BENEFIT:
        dataScope: "education,employment,skills"
        purpose: "verification"
        requestingDepartmentId: "DEPT-SKILLS"
        requiredFields: "fullName,dateOfBirth,highestDegree,employmentStatus,skillStatus"
        optionalFields: "annualFamilyIncome"
      SCHOLARSHIP:
        dataScope: "education"
        purpose: "scholarship_verification"
        requestingDepartmentId: "DEPT-EDU"
        requiredFields: "fullName,dateOfBirth,highestDegree,universityName"
        optionalFields: "annualFamilyIncome"
      SRV-EDU:
        dataScope: "education,health"
        purpose: "verification"
        requestingDepartmentId: "DEPT-HLTH"
        requiredFields: "fullName,dateOfBirth,highestDegree,universityName"
        optionalFields: "annualFamilyIncome"

logging:
  level:
    com.mahasetu.securityworkflow: INFO
