server:
  port: 8082

spring:
  application:
    name: interoperability-service
  cache:
    cache-names: citizenData
    caffeine:
      spec: expireAfterWrite=10m,maximumSize=1000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/mahasetu
          jwk-set-uri: http://keycloak:8080/realms/mahasetu/protocol/openid-connect/certs

resilience4j:
  circuitbreaker:
    instances:
      externalService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
